### ISSUE TITLE
Feature request: Single sign out. 

### ISSUE THREAD

**Issue by Romeren** [travisghansen/external-auth-server#38]
Correct me if im wrong or if this belongs somewhere completely else, feel free to remove this request all together.

As far as i understand, in order to sign out from key cloak you will need:
- Keycloak url
- Realm
- Client secret
- Token
- Refresh token

I'm a bit reluctant to start hard coding these variables into my back-end, which ideally shouldn't know anything about the whole SSO circus.

Instead, i would suggest (since the EAS already gets all these informations in the config-token supplied by each request) the creation of either:
- An endpoint on the EAS to sign as user out from a client
- A header passed to the EAS that will sign the user out from a client

I'm happy to hear your thoughts on this one :)

**Comment by travisghansen** [comment]
This is a great idea! I'll do some research to have a better understanding of how this should work in the ecosystem and if it's a fit I'm sure we can add something.

**Comment by Romeren** [comment]
Great to hear..!
Let me know if there is anything i can help with :)

**Comment by travisghansen** [comment]
I'm currently at kubecon so might be a bit before a can get back to you..

**Comment by fgather** [comment]
is there any update on this topic? :)

**Comment by travisghansen** [comment]
Sorry not yet :( but I haven't forgotten about you :)

I'm generally going for a 1.0 release which will have some minor breaking changes and hopefully implement this and some other remaining requests.

**Comment by travisghansen** [comment]
I haven't read all the specs yet but I'm digging through this article here: https://medium.com/@robert.broeckelmann/openid-connect-logout-eccc73df758f

In general this is quite involved (or at least appears to be). Do you want the sign out to log out of eas only or all sessions they have with the provider? Perhaps read through that a bit and we can start to solidify the vision a bit more.

Thanks!

**Comment by Romeren** [comment]
Hmmm good question..... ill have to read a bit to get a grasp of the implications.

I imagine though that signing out of eas only is preferable. But ill read some docs and get back to you.

Thanks for getting back to it though 👍

**Comment by travisghansen** [comment]
Yeah no problem. Just wiping the session with `eas` is quite simple. If we're looking to fully invalidate the token (before it expires) then it looks like things get pretty interesting.

**Comment by travisghansen** [comment]
Any more thought on this? I'm going to put some work in this project over the next couple days..

**Comment by kettenbach-it** [comment]
I'm very much interested in this. I'm using oidc with google.

**Comment by travisghansen** [comment]
Well, since the session is server side we can simply delete the session and the cookie becomes irrelevant...same as if the session expired.

If you don't mind read through the medium article linked in the above comment for some other thoughts about real signout (vs invalidating the `eas` session) and we'll see what makes the most sense.

**Comment by kettenbach-it** [comment]
I briefly read the medium article. 
I still don't know much about OICD/OAuth but considering the medium article, I notice with gsuite (I'm a user of Google-Gsuite) that I can't log out of individual applications or individual accounts. Google only provides the button "Log out of all accounts", which implies "all applications of all accounts"  - at least those of Google (GMail, Calender etc.). They seem to share the same security session.

When it comes to my own application that I started to use eas for, the requirement would be:
- I don't have the need to destroy the session globally. Just on eas. Which means the following flow:
- The users navigates to a logout-url by a simple anchor tag in the UI linking to eas. E.g. https://eas.mydomain.com/signout
- eas will destroy the session it recognizes
- eas will redirect to a logout url provided in the config_token or in the individual request, e.g. https://www.mydomain.com/you_sucessfully_logged_out
- in case of an error, redirect to an error url

Maybe folks like eas to display the success and error message, but I think - since eas is supposed to be completely hidden for the user - that this is the job of the application it's securing.

**Comment by travisghansen** [comment]
Yeah, I think that's easy enough to implement a crude version of that. I'd make the redirect uri a GET param to the sign-out URL (same as oauth/oidc using `redirect_uri` param). I'll implement this in my current round of enhancements.

**Comment by travisghansen** [comment]
`eas` session destruction has been implemented in `next`. You can create a URL that will land *somewhere* that would invoke a particular plugin with special `GET` parameters.

```
https://svc.example.com?__eas_oauth_handler__=logout&redirect_uri=https%3A%2F%2Fgithub.com
```

Try it out and provide any feedback you can. Thanks!

**Comment by kettenbach-it** [comment]
If I call

`https://auth.mydomain.com?__eas_oauth_handler__=logout&redirect_uri=.....`

the request if redirected to:

`https://auth.mydomain.com/?__eas_oauth_handler__=logout&redirect_uri=.....`

("/" after domain) and the result is:

<pre>Cannot GET /</pre>

This might be my loadbalancer rhat doesn't like urls with a parameter appended to the domain.
Wouldn't it be nicer to use a URL like:

`https://svc.example.com/oauthlogout?redirect=.....`

**Comment by travisghansen** [comment]
Don't point it at the `eas` service directly. Point it any arbitrary url where `eas` will get invoked by the forward auth.

**Comment by kettenbach-it** [comment]
Same thing: the "/" is added and that's it!

**Comment by travisghansen** [comment]
Not sure I follow that last comment.

Some explanation on pushing through an endpoint that's invoking the forward auth vs a direct endpoint...since the configuration of `eas` is dynamic (ie: stored in the URL or a header) such that a single deployment can handle infinite number of configurations, it becomes impossible to *sanely* know what session to kill if the service is invoked directly without all the normal context from an actual endpoint where the specific config (ie: `plugins`, etc) are involved.

A generic direct endpoint *could* be created but proper operation would be happenstance and limited to strictly defaults and using *lots* of assumptions.

**Comment by travisghansen** [comment]
I will add, it can be literally *any* URL that would invoke the forward auth mechanism. Just add the special `GET` params to the request. For example:

```
https://svc.example.com/api/v1/foo/bar/baz?__eas_oauth_handler__=logout&redirect_uri=https%3A%2F%2Fgithub.com
```

would work just fine assuming `svc.example.com` is protected by `eas`.

**Comment by kettenbach-it** [comment]
I checked again.

If I add "?__eas_oauth_handler__=logout&redirect_uri=https%3A%2F%2Fgithub.com" to the root (https://www.mydomain.com?__eas_oauth_handler...) nothing happens but the "/" is inserted between the domain und URL => https://www.mydomain.com/?__eas_o

If I add the parameter do any path, nothing happens at all. 

The request is routed to the backend service as shown in the log:

`mydomain-api        | 172.30.0.16 - - [28/Feb/2020:16:53:37 +0100] "GET /?__eas_oauth_handler__=logout&redirect_uri=https%3A%2F%2Fgithub.com HTTP/1.1" 200 3656 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"`

**Comment by travisghansen** [comment]
`www.mydomain.com` is protected by `eas` with your proxy?

**Comment by travisghansen** [comment]
This might sound silly but did you restart `eas` after pulling the latest code?

**Comment by kettenbach-it** [comment]
D'Oh!
I'm very sorry. I forgot to raise the version tag of the docker image. Therefore i started the old one. Now it works!

**Comment by travisghansen** [comment]
Beautiful!

**Comment by travisghansen** [comment]
This has landed in master/latest. Documentation will be added shortly.
