### ISSUE TITLE
Having a hard time configuring this.

### ISSUE THREAD

**Issue by solipsist01** [travisghansen/external-auth-server#41]
Hello.

I'm trying to incorporate this into Traefik v2.0 in combination with Keycloak.
Traefik v2.0 allows configuring for a serperate forward authentication middleware, which then can be attached on a per container basis.

I could then, attach this forward authentication middleware, to each container, allowing for single signon to all my microservices.

However, in Keycloak i have to configure a Base URL, Root URL, etc.
This would mean i could only use one URL ?

how should my Client configuration in my Keycloak realm look like in order to make this work ?
Do i need to proxy the EAS port 8080, and configure that as a Root URL,

Can anyone point me into the right direction ?

**Comment by solipsist01** [comment]
I managed to figure it out :)
the redirect url should be to eas in the .js config, and the keycloak URLS should be empty.

**Comment by travisghansen** [comment]
@solipsist01 glad you figured it out! You basically have 2 options:

1. do not set a redirect URL in the `config_token` and set a wildcard in keycloak
2. set the redirect URL in the `config_token` and the appropriate URL in keycloak

I generally recommend the 2nd option. In which case you do need to expose `eas` directly to clients however. In your config you would put: `redirect_uri: 'https://eas.example.com/oauth/callback'` and then the same URL in keycloak. The advantage of this route is it enables SSO with a single cookie getting created across services (you would still get SSO otherwise, just new cookies/sessions per-service however). In the same example, you would set `cookie.domain: 'example.com'`.

Hope this helps and thanks for the interest!
