### ISSUE TITLE
OIDC with dash sign in URL

### ISSUE THREAD

**Issue by egona** [travisghansen/external-auth-server#82]
This issue is about logging in with OIDC. It seems that EAS gets confused if the login URL (appliation URL) contains a dash (#), e.g.:
 
   https://myserver.dummy.org/client#/overzicht?license=cafe&place=amsterdam

If you open that URL, EAS will redirect the browser to the authorization endpoint of the OpenID provider. The redirect URL contains, amongst other things, a "redirect_uri" parameter for the callback and an encoded "state" parameter. 

I suspect that the state parameter contains a truncated version of the application URL: it doesn't include the part after the dash (i.e. "#/overzicht?license=cafe&place=amsterdam").

Upon receiving the redirect, the browser opens the redirect URL but then also appends the dash part to it:

   redirect-URL + "#/overzicht?license=cafe&place=amsterdam"

 Once logged in, the browser will then be redirected to the truncated application URL:

   https://myserver.dummy.org/client   

I hope someone can confirm that the dash is indeed causing the problem, and if there is any workaround or fix for it.

- Egon

**Comment by travisghansen** [comment]
Just to be clear, you mean the pound sign not dash right?

I’ll do some research but is everything after the # considered the URL fragment in your scenario? Or is that data considered part of the path?

Fragments are completely a browser/client side thing and actually aren’t sent to webservers so that may make this one difficult.

Lastly, what proxy are you working with so I can observe the specific behavior?

**Comment by egona** [comment]
Yes, I was mistaken with the pound/hash sign. It is indeed an URL fragment and I didn't realize it wasn't sent to the webserver. Thanks for pointing that out. The issue can be closed. We use eas in conjunction with traefik btw.

**Comment by travisghansen** [comment]
Very cool. Thanks for the interest in the project, glad it's of use!
