### ISSUE TITLE
oidc introspection not working

### ISSUE THREAD

**Issue by djbulsink** [travisghansen/external-auth-server#84]
Hi Travis, 

I would like to use the oidc access token introspection feature for a project. But it is not working when using a discover_url. In the eas log I this error message:

```
{"message":"issuer does not support introspection","level":"error","service":"external-auth-server"}
```

In our oidc metadata there is an "introspection_endpoint" provided. This is according correct to https://tools.ietf.org/html/rfc8414 .

I assume it is caused by this line:
https://github.com/travisghansen/external-auth-server/blob/master/src/plugin/oauth/index.js#L1254

I guess it should be 
```
      if (!issuer.metadata.introspection_endpoint) {
```

Instead of:
```
      if (!issuer.metadata.token_introspection_endpoint) {
```

**Comment by travisghansen** [comment]
Hmm could be. That’s not an often used feature I guess so the logic may need some help.

Let me see if I can find an issuer that supports that and get a fix out real quick...

**Comment by travisghansen** [comment]
OK, I've got this cleaned up and implemented a cache mechanism and parameter around it as well (ie: cache (valid) introspection responses for X seconds to reduce the sub-request overhead). I'll commit as a point release in the next little bit.

**Comment by travisghansen** [comment]
Landed in `latest` and `v0.9.1`. Try it out and let me know how it goes.

**Comment by djbulsink** [comment]
Works like a charm, thank you very much for the quick solution.

**Comment by Electrofenster** [comment]
@travisghansen why does the jwt plugin don't use the introspection endpoint to validate that the accessToken is still valid.
When I logout all my sessions in keycloak for the previously authenticated user the accessToken is still valid. I think that's because the jwt plugin don't uses the introspection endpoint to validate the accessToken?

**Comment by travisghansen** [comment]
@Electrofenster strictly speaking jwt can be used outside of oauth/oidc so it not necessarily implied those are being used (and by extension the introspection feature of the specs) when using basic jwt. It could be added however to the project to support that. Let’s open another ticket to get your requests sorted out. It’s good timing because I’ve got some other minor tweaks to make to the project upcoming :)
